### ISSUE TITLE
内部動作(CT,ダッシュ)

### ISSUE THREAD

**Issue by Hida00** [koyosai-4I-2022/Koyosai22-Gameclient#6]
攻撃の間隔を設定する(連続して攻撃を出来ないようにするもしくはダメージを低くする)
相手との距離を詰めるダッシュの実装

**Comment by Hida00** [comment]
制限時間になったらゲームを終了させる

**Comment by tmtmNasubi** [comment]
実装手順

1. タイマーを実装して終了させられるようにする
2. 攻撃判定のループにディレイをかける
3. ボタンを押したら短時間速度を上昇させる
